# Generated by Django 4.1 on 2022-08-21 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a task name', max_length=200)),
                ('description', models.CharField(help_text='Description of the task', max_length=1000)),
                ('contributors', models.ManyToManyField(help_text='List of contributors', to='catalog.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular task across whole board', primary_key=True, serialize=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('w', 'in work'), ('fn', 'finished'), ('fr', 'frozen')], default='w', help_text='task status', max_length=2)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.task')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
