# Generated by Django 4.1 on 2022-08-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_board_alter_task_options_remove_task_contributors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
    ]
