# Generated by Django 4.1 on 2022-08-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['name']},
        ),
    ]
